<a href="https://colab.research.google.com/github/Ian386/LUX_ADMY-DS-BTCMP/blob/main/OUTLIER_DETECTION_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/heights.csv')

In [ ]:
max_threshold = df['height'].quantile(0.95)

In [ ]:
df[df['height'] > max_threshold]

    name  height
9  imran    14.5

In [ ]:
 min_threshold = df['height'].quantile(0.05)

In [ ]:
df[df['height'] < min_threshold]

      name  height
12  yoseph     1.2

In [ ]:
df[(df['height'] < max_threshold) & (df['height'] > min_threshold)]

       name  height
0     mohan     5.9
1     maria     5.2
2     sakib     5.1
3       tao     5.5
4     virat     4.9
5    khusbu     5.4
6    dmitry     6.2
7    selena     6.5
8      john     7.1
10     jose     6.1
11  deepika     5.6
13    binod     5.5

In [ ]:
df = pd.read_csv('/content/bhp.csv')

In [ ]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13200.000000  13200.000000  13200.000000  13200.000000    1.320000e+04
mean    1555.302783      2.691136    112.276178      2.800833    7.920337e+03
std     1237.323445      1.338915    149.175995      1.292843    1.067272e+05
min        1.000000      1.000000      8.000000      1.000000    2.670000e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.267000e+03
50%     1275.000000      2.000000     71.850000      3.000000    5.438000e+03
75%     1672.000000      3.000000    120.000000      3.000000    7.317000e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [ ]:
min_threshold, max_threshold = df.price_per_sqft.quantile([0.001, 0.999])
min_threshold, max_threshold

(1366.184, 50959.36200000098)

In [ ]:
df[df.price_per_sqft < min_threshold]

        location       size  total_sqft  bath  price  bhk  price_per_sqft
665    Yelahanka      3 BHK     35000.0   3.0  130.0    3             371
798        other  4 Bedroom     10961.0   4.0   80.0    4             729
1867       other  3 Bedroom     52272.0   2.0  140.0    3             267
2392       other  4 Bedroom      2000.0   3.0   25.0    4            1250
3934       other      1 BHK      1500.0   1.0   19.5    1            1300
5343       other      9 BHK     42000.0   8.0  175.0    9             416
5417      Ulsoor      4 BHK     36000.0   4.0  450.0    4            1250
5597    JP Nagar      2 BHK      1100.0   1.0   15.0    2            1363
7166   Yelahanka  1 Bedroom     26136.0   1.0  150.0    1             573
7862    JP Nagar      3 BHK     20000.0   3.0  175.0    3             875
8300     Kengeri      1 BHK      1200.0   1.0   14.0    1            1166
9144       other  4 Bedroom     10961.0   4.0   80.0    4             729
11635      Begur      3 BHK      2400.0   3.0   12.0    3             500
12355      other      4 BHK     16335.0   4.0  149.0    4             912

In [ ]:
df[df.price_per_sqft > max_threshold]

,location,size,total_sqft,bath,price,bhk,price_per_sqft
345,other,3 Bedroom,11.0,3.0,74.0,3,672727
1005,other,1 BHK,15.0,1.0,30.0,1,200000
1106,other,5 Bedroom,24.0,2.0,150.0,5,625000
4044,Sarjapur Road,4 Bedroom,1.0,4.0,120.0,4,12000000
4924,other,7 BHK,5.0,7.0,115.0,7,2300000
5911,Mysore Road,1 Bedroom,45.0,1.0,23.0,1,51111
6356,Bommenahalli,4 Bedroom,2940.0,3.0,2250.0,4,76530
7012,other,1 BHK,650.0,1.0,500.0,1,76923
7575,other,1 BHK,425.0,1.0,750.0,1,176470
7799,other,4 BHK,2000.0,3.0,1063.0,4,53150
8307,Bannerghatta Road,5 BHK,2500.0,4.0,1400.0,5,56000
9436,Indira Nagar,4 Bedroom,2400.0,5.0,1250.0,4,52083
11447,Whitefield,4 Bedroom,60.0,4.0,218.0,4,363333
12328,other,4 Bedroom,4350.0,8.0,2600.0,4,59770

In [ ]:
df[(df['price_per_sqft'] < max_threshold) & (df['price_per_sqft'] > min_threshold)]
df.shape

(13200, 7)

In [ ]:
df.sample(10)

,location,size,total_sqft,bath,price,bhk,price_per_sqft
8869,Kaggadasapura,3 Bedroom,2500.0,5.0,120.0,3,4800
162,other,3 BHK,2000.0,3.0,175.0,3,8750
1235,Lakshminarayana Pura,2 BHK,1180.0,2.0,75.0,2,6355
938,Sahakara Nagar,3 BHK,1500.0,2.0,95.0,3,6333
6696,Chamrajpet,1 BHK,505.0,1.0,85.0,1,16831
8222,Bommanahalli,3 BHK,1660.0,2.0,100.0,3,6024
3297,Basaveshwara Nagar,2 BHK,1200.0,2.0,90.0,2,7500
2105,Kumaraswami Layout,4 Bedroom,2000.0,4.0,139.0,4,6950
1501,Kaggalipura,2 BHK,950.0,2.0,39.0,2,4105
10486,Whitefield,3 BHK,1760.0,3.0,160.0,3,9090

In [ ]:
q1 = df['price_per_sqft'].quantile(0.25)
q3 = df['price_per_sqft'].quantile(0.75)
iqr = q3 - q1
q1, q3, iqr

(4267.0, 7317.0, 3050.0)

In [ ]:
lower_limit = q1 - 1.5*iqr
upper_limit = q3 + 1.5*iqr
lower_limit, upper_limit

(-308.0, 11892.0)

In [ ]:
df[(df['price_per_sqft'] > max_threshold) | (df['price_per_sqft'] < min_threshold)]

,location,size,total_sqft,bath,price,bhk,price_per_sqft
345,other,3 Bedroom,11.0,3.0,74.0,3,672727
665,Yelahanka,3 BHK,35000.0,3.0,130.0,3,371
798,other,4 Bedroom,10961.0,4.0,80.0,4,729
1005,other,1 BHK,15.0,1.0,30.0,1,200000
1106,other,5 Bedroom,24.0,2.0,150.0,5,625000
1867,other,3 Bedroom,52272.0,2.0,140.0,3,267
2392,other,4 Bedroom,2000.0,3.0,25.0,4,1250
3934,other,1 BHK,1500.0,1.0,19.5,1,1300
4044,Sarjapur Road,4 Bedroom,1.0,4.0,120.0,4,12000000
4924,other,7 BHK,5.0,7.0,115.0,7,2300000
5343,other,9 BHK,42000.0,8.0,175.0,9,416
5417,Ulsoor,4 BHK,36000.0,4.0,450.0,4,1250
5597,JP Nagar,2 BHK,1100.0,1.0,15.0,2,1363
5911,Mysore Road,1 Bedroom,45.0,1.0,23.0,1,51111
6356,Bommenahalli,4 Bedroom,2940.0,3.0,2250.0,4,76530
7012,other,1 BHK,650.0,1.0,500.0,1,76923
7166,Yelahanka,1 Bedroom,26136.0,1.0,150.0,1,573
7575,other,1 BHK,425.0,1.0,750.0,1,176470
7799,other,4 BHK,2000.0,3.0,1063.0,4,53150
7862,JP Nagar,3 BHK,20000.0,3.0,175.0,3,875
8300,Kengeri,1 BHK,1200.0,1.0,14.0,1,1166
8307,Bannerghatta Road,5 BHK,2500.0,4.0,1400.0,5,56000
9144,other,4 Bedroom,10961.0,4.0,80.0,4,729
9436,Indira Nagar,4 Bedroom,2400.0,5.0,1250.0,4,52083
11447,Whitefield,4 Bedroom,60.0,4.0,218.0,4,363333
11635,Begur,3 BHK,2400.0,3.0,12.0,3,500
12328,other,4 Bedroom,4350.0,8.0,2600.0,4,59770
12355,other,4 BHK,16335.0,4.0,149.0,4,912

In [ ]:
df[(df['price_per_sqft'] < max_threshold) & (df['price_per_sqft'] > min_threshold)]
df.shape

(13200, 7)